- name: Node Exporter 설치
  hosts: all:!monitoring
  become: true
  tasks:
    - name: Node Exporter 바이너리 다운로드
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
        dest: /tmp/node_exporter.tar.gz

    - name: 압축 해제
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /opt/
        remote_src: yes

    - name: 기존 node_exporter 바이너리 제거 (파일로 존재할 경우)
      file:
        path: /usr/local/bin/node_exporter
        state: absent
      when: >
        ansible_facts['user_id'] is defined and
        (ansible_facts['user_id'] != 'root' or
        (ansible_facts['user_id'] == 'root' and
        lookup('file', '/usr/local/bin/node_exporter', errors='ignore') != ''))

    - name: 심볼릭 링크 생성
      file:
        src: /opt/node_exporter-1.7.0.linux-amd64/node_exporter
        dest: /usr/local/bin/node_exporter
        state: link
        force: yes

    - name: systemd 서비스 등록
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/node_exporter
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: 서비스 시작 및 활성화
      systemd:
        name: node_exporter
        enabled: yes
        state: started

- name: Docker 기반 모니터링 스택 설치 (Prometheus, Grafana, Alertmanager)
  hosts: monitoring
  become: true
  vars:
    local_project_root: ../../infra-components/monitoring
    monitoring_base_dir: /opt/monitoring
        
  tasks:
    - name: Ensure Docker is installed
      include_role:
        name: common

    - name: 모니터링 디렉토리 구성
      file:
        path: "{{ monitoring_base_dir }}"
        state: directory
        recurse: yes
    
    - name: docker-compose.yml 배포
      copy:
        src: "{{ local_project_root }}/docker-compose.yml"
        dest: "{{ monitoring_base_dir }}/docker-compose.yml"

    - name: Docker Compose로 스택 실행
      shell: |
        cd {{ monitoring_base_dir }} && docker-compose up -d

    - name: Prometheus 설정 파일 배포
      copy:
        src: "{{ local_project_root }}/prometheus.yml"
        dest: "{{ monitoring_base_dir }}/prometheus.yml"

    - name: Grafana 디렉토리 생성
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ monitoring_base_dir }}/grafana/provisioning/datasources"
        - "{{ monitoring_base_dir }}/grafana/provisioning/dashboards"

    - name: Grafana datasource 설정 복사
      copy:
        src: "{{ local_project_root }}/grafana/datasources.yml"
        dest: "{{ monitoring_base_dir }}/grafana/provisioning/datasources/datasources.yml"

    - name: Grafana dashboard 설정 복사
      copy:
        src: "{{ local_project_root }}/grafana/dashboards.yml"
        dest: "{{ monitoring_base_dir }}/grafana/provisioning/dashboards/dashboards.yml"

    - name: Grafana node_exporter dashboard 복사
      copy:
        src: "{{ local_project_root }}/grafana/node_exporter_dashboard.json"
        dest: "{{ monitoring_base_dir }}/grafana/dashboards/node_exporter_dashboard.json"

    - name: Alertmanager 디렉토리 생성
      file:
        path: "{{ monitoring_base_dir }}/alertmanager"
        state: directory

    - name: rules 디렉토리 생성
      file:
        path: "{{ monitoring_base_dir }}/rules"
        state: directory

    - name: Alertmanager 설정 파일 복사
      copy:
        src: "{{ local_project_root }}/alertmanager/alertmanager.yml"
        dest: "{{ monitoring_base_dir }}/alertmanager/alertmanager.yml"

    - name: Prometheus Alert Rules 복사
      copy:
        src: "{{ local_project_root }}/rules/alert_rules.yml"
        dest: "{{ monitoring_base_dir }}/rules/alert_rules.yml"

    # GlusterFS 설치 및 마운트
    - name: install glusterfs
      apt:
        name: glusterfs-client
        state: present

    - name: unmount glusterfs
      shell: |
        umount -l /shared/mnt/logs/monitoring
      ignore_errors: true

    - name: Remove mount dir monitoring logs
      file:
        path: /shared/mnt/logs/monitoring
        state: absent
      ignore_errors: true

    - name: Create mount dir monitoring logs
      file:
        path: /shared/mnt/logs/monitoring
        state: directory
        mode: '0777'

    - name: GlusterFS mount monitoring logs
      mount:
        path: "/shared/mnt/logs/monitoring"
        src: "172.16.1.40:monitoring"
        fstype: glusterfs
        opts: defaults,_netdev
        state: mounted

    - name: Change ownership of Prometheus log directory to 'nobody'
      file:
        path: /shared/mnt/logs/monitoring
        state: directory
        owner: 65534
        group: 65534
        recurse: yes